// nextjs/src/components/share/groupPopover.tsx
"use client";
import { Box, Button, Popover, TextField } from "@mui/material";
import AutocompleteInput from "../autocompleteInput";

type GroupPopoverProps = {
    anchorEl: HTMLButtonElement | null;
    onClose: () => void;
    onSubmit: (groupName: string) => Promise<boolean>;
    label: string;
    type: "new" | "join";
};


export default function GroupPopover({
    anchorEl,
    onClose,
    onSubmit,
    label,
    type
}: Readonly<GroupPopoverProps>) {
    const open = Boolean(anchorEl);

    async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        const formData = new FormData(e.currentTarget);
        const groupName = formData.get("groupName") as string;

        console.log(groupName);

        try {
            const res = await onSubmit(groupName);
            if (res) {
                onClose();
            }
        } catch (err: unknown) {
            console.error(err);
        }
    }

    return (
        <Popover
            open={open}
            anchorEl={anchorEl}
            onClose={onClose}
            anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
            transformOrigin={{ vertical: "top", horizontal: "center" }}
        >
            <Box
                component="form"
                onSubmit={handleSubmit}
                p={2}
                width={300}
            >
                {type == "new" &&
                    <TextField
                        label={label}
                        name="groupName"
                        fullWidth
                        size="small"
                        autoFocus
                    />
                }
                {type == "join" &&
                    <AutocompleteInput
                        suburl="group"
                        label={label}
                        name="groupName"
                    />
                }
                <Box mt={2} display="flex" justifyContent="flex-end" gap={1}>
                    <Button
                        variant="outlined"
                        size="small"
                        onClick={onClose}
                    >
                        Cancel
                    </Button>
                    <Button
                        type="submit"
                        variant="contained"
                        size="small"
                    >
                        {type == "new" ? "Create" : "Join"}
                    </Button>
                </Box>
            </Box>
        </Popover>
    );
}

// vue/src/components/GroupPopover.vue
<template>
  <div
    v-if="open"
    class="fixed inset-0 z-40 flex items-center justify-center bg-black/40"
    @click.self="onClose"
  >
    <div class="bg-white rounded-lg shadow-lg p-4 w-full max-w-sm">
      <form @submit.prevent="handleSubmit">
        <div v-if="type === 'new'" class="mb-4">
          <label for="groupName" class="block text-sm font-medium mb-2">
            {{ label }}
          </label>
          <input
            id="groupName"
            v-model="groupName"
            type="text"
            name="groupName"
            class="w-full border rounded px-3 py-2"
            autofocus
            required
          />
        </div>

        <div v-if="type === 'join'" class="mb-4">
          <label for="groupName" class="block text-sm font-medium mb-2">
            {{ label }}
          </label>
          <input
            id="groupName"
            v-model="groupName"
            type="text"
            name="groupName"
            class="w-full border rounded px-3 py-2"
            autofocus
            required
          />
        </div>

        <div class="flex justify-end gap-2">
          <button
            type="button"
            class="px-4 py-2 text-gray-700 border rounded hover:bg-gray-50"
            @click="onClose"
          >
            Cancel
          </button>
          <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
            {{ type === 'new' ? 'Create' : 'Join' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

interface Props {
  anchorEl: HTMLElement | null
  onClose: () => void
  onSubmit: (groupName: string) => Promise<boolean>
  label: string
  type: 'new' | 'join'
}

const props = defineProps<Props>()

const groupName = ref('')
const open = computed(() => !!props.anchorEl)

const handleSubmit = async () => {
  try {
    const res = await props.onSubmit(groupName.value)
    if (res) {
      groupName.value = ''
      props.onClose()
    }
  } catch (err: unknown) {
    console.error(err)
  }
}
</script>
