// vue/src/components/share/SharePopover.vue
<template>
  <div
    v-if="open"
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/40"
    @click.self="emit('close')"
  >
    <div
      class="dive-card bg-white dark:bg-gray-800 rounded-xl shadow-lg flex flex-col w-full max-w-md max-h-[70vh]"
    >
      <!-- Header -->
      <div class="flex items-center gap-2 px-4 py-3 border-b shrink-0">
        <button
          v-if="view !== 'overview'"
          @click="view = 'overview'"
          class="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded"
        >
          ←
        </button>
        <span class="font-medium text-sm">
          {{ viewTitle }}
        </span>
      </div>

      <!-- Body (scrollable) -->
      <div class="flex-1 overflow-y-auto px-4 py-3">
        <!-- Overview -->
        <div v-if="view === 'overview'" class="space-y-4">
          <!-- People Section -->
          <section>
            <div class="flex items-center justify-between mb-2">
              <span class="text-xs font-semibold text-gray-600 dark:text-gray-400">People</span>
              <button
                @click="view = 'add-person'"
                class="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded text-blue-600"
              >
                +
              </button>
            </div>
            <ul class="space-y-1">
              <li
                v-for="person in readers"
                :key="person.id"
                class="flex justify-between items-center py-1"
              >
                <span class="text-sm">{{ person.name }}</span>
                <button
                  @click="deletePerson(person.id)"
                  class="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded text-red-600"
                >
                  ×
                </button>
              </li>
              <li v-if="readers.length === 0" class="text-sm text-gray-400 dark:text-gray-500">
                No people shared
              </li>
            </ul>
          </section>

          <!-- Groups Section -->
          <section>
            <div class="flex items-center justify-between mb-2">
              <span class="text-xs font-semibold text-gray-600 dark:text-gray-400">Groups</span>
              <button
                @click="view = 'add-group'"
                class="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded text-blue-600"
              >
                +
              </button>
            </div>
            <ul class="space-y-1">
              <li
                v-for="group in groupReaders"
                :key="group.id"
                class="flex justify-between items-center py-1"
              >
                <span class="text-sm">{{ group.name }}</span>
                <button
                  @click="deleteGroup(group.id)"
                  class="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded text-red-600"
                >
                  ×
                </button>
              </li>
              <li v-if="groupReaders.length === 0" class="text-sm text-gray-400 dark:text-gray-500">
                No groups shared
              </li>
            </ul>
          </section>
        </div>

        <!-- Add Person -->
        <form
          v-else-if="view === 'add-person'"
          @submit.prevent="handleAddPerson"
          class="flex flex-col gap-4"
        >
          <div class="flex flex-col gap-2">
            <label class="text-sm font-medium">Enter username</label>
            <input
              v-model="personInput"
              type="text"
              placeholder="Username..."
              class="border rounded-lg p-2"
              autofocus
            />
          </div>
          <button
            type="submit"
            class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg"
          >
            Add buddy
          </button>
        </form>

        <!-- Add Group -->
        <form
          v-else-if="view === 'add-group'"
          @submit.prevent="handleAddGroup"
          class="flex flex-col gap-4"
        >
          <div class="flex flex-col gap-2">
            <label class="text-sm font-medium">Enter group name</label>
            <input
              v-model="groupInput"
              type="text"
              placeholder="Group name..."
              class="border rounded-lg p-2"
              autofocus
            />
          </div>
          <button
            type="submit"
            class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg"
          >
            Add group
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { toast } from 'vue-sonner'
import { useApi } from '@/composables/useApi'
import type { User, Group } from '@/lib/types/share'
import type { PagedResult } from '@/lib/types/dive'

const props = defineProps<{
  open: boolean
  diveId: number | undefined
}>()

const emit = defineEmits<{
  close: []
}>()

type View = 'overview' | 'add-person' | 'add-group'

const view = ref<View>('overview')
const readers = ref<User[]>([])
const groupReaders = ref<Group[]>([])
const personInput = ref('')
const groupInput = ref('')

const { getWithToken, postWithToken, deleteWithToken } = useApi()

const viewTitle = computed(() => {
  switch (view.value) {
    case 'overview':
      return 'Dive shared with'
    case 'add-person':
      return 'Add person'
    case 'add-group':
      return 'Add group'
    default:
      return '' // ESLint
  }
})

watch(
  () => props.open,
  async (isOpen) => {
    if (isOpen) {
      view.value = 'overview'
      await fetchAllReaders()
    }
  },
)

const fetchAllReaders = async () => {
  if (props.diveId == null) return

  try {
    const [readersRes, groupsRes] = await Promise.all([
      getWithToken<PagedResult<User>>(`/v1/dives/${props.diveId}/readers`),
      getWithToken<Group[]>(`/v1/dives/${props.diveId}/group-readers`),
    ])
    readers.value = readersRes.data.result
    groupReaders.value = groupsRes.data
  } catch (err) {
    console.error('Failed to fetch readers', err)
  }
}

const deletePerson = async (id: number) => {
  if (props.diveId == null) return
  try {
    await deleteWithToken(`/v1/dives/${props.diveId}/readers`, [id])
    toast.success('Removed person')
    await fetchAllReaders()
  } catch (err) {
    toast.error('Failed to remove person')
    console.error(err)
  }
}

const deleteGroup = async (id: number | undefined) => {
  if (props.diveId == null || id == null) return
  try {
    await deleteWithToken(`/v1/dives/${props.diveId}/group-readers?groupId=${id}`)
    toast.success('Removed group')
    await fetchAllReaders()
  } catch (err) {
    toast.error('Failed to remove group')
    console.error(err)
  }
}

const handleAddPerson = async () => {
  if (props.diveId == null || !personInput.value.trim()) return
  try {
    await postWithToken(`/v1/dives/${props.diveId}/readers`, [personInput.value])
    toast.success('Added person')
    personInput.value = ''
    view.value = 'overview'
    await fetchAllReaders()
  } catch (err) {
    toast.error('Failed to add person')
    console.error(err)
  }
}

const handleAddGroup = async () => {
  if (props.diveId == null || !groupInput.value.trim()) return
  try {
    await postWithToken(`/v1/dives/${props.diveId}/group-readers`, groupInput.value)
    toast.success('Added group')
    groupInput.value = ''
    view.value = 'overview'
    await fetchAllReaders()
  } catch (err) {
    toast.error('Failed to add group')
    console.error(err)
  }
}
</script>

<style scoped>
.dive-card {
  background-color: var(--card-bg);
  box-shadow: 0 10px 28px rgba(0, 0, 0, 0.12);
}

[data-theme='dark'] .dive-card {
  box-shadow: 0 12px 30px rgba(0, 0, 0, 0.35);
}
</style>

// nextjs/src/components/share/sharePopover.tsx
"use client";

import useApi from "@/hooks/useApi";
import { PagedResult } from "@/types/dive";
import { Group, User } from "@/types/share";
import AddIcon from "@mui/icons-material/Add";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import CrossIcon from "@mui/icons-material/Close";
import IconButton from "@mui/material/IconButton";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import Popover from "@mui/material/Popover";
import { useCallback, useEffect, useState } from "react";
import { toast } from "react-toastify";
import AutocompleteInput from "../autocompleteInput";

// ---- Types ----
type View = "overview" | "add-person" | "add-group";

type Props = {
  anchorEl: HTMLElement | null;
  onClose: () => void;
  diveId: number | undefined;
};

// ---- Main component ----
export default function SharePopover({
  anchorEl,
  onClose,
  diveId,
}: Readonly<Props>) {
  const [view, setView] = useState<View>("overview");
  const [readers, setReaders] = useState<User[]>([]);
  const [groupReaders, setGroupReaders] = useState<Group[]>([]);

  const { getWithToken } = useApi();

  const open = Boolean(anchorEl);

  const fetchAllReaders = useCallback(async () => {
    if (diveId == null) return null;

    try {
      return await Promise.all([
        getWithToken<PagedResult<User>>(`/v1/dives/${diveId}/readers`),
        getWithToken<Group[]>(`/v1/dives/${diveId}/group-readers`),
      ]).then(([r, g]) => ({ readers: r.data, groups: g.data }));
    } catch (err: unknown) {
      console.log(err);
      return null;
    }
  }, [diveId, getWithToken]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const result = await fetchAllReaders();
      if (result == null) {
        return;
      }
      const { readers, groups } = result;
      if (cancelled) {
        return;
      }
      setReaders(readers.result);
      setGroupReaders(groups);
    })();
    return () => {
      cancelled = true;
    };
  }, [diveId, fetchAllReaders]);

  return (
    <Popover
      open={open}
      anchorEl={anchorEl}
      onClose={onClose}
      anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
      transformOrigin={{ vertical: "top", horizontal: "right" }}
    >
      <div className="flex flex-col h-full min-h-0 max-h-70 w-70">
        {/* Header */}
        <div className="flex flex-none h-10 items-center gap-2 px-4 py-2 border-b">
          {view !== "overview" && (
            <IconButton size="small" onClick={() => setView("overview")}>
              <ArrowBackIcon fontSize="small" />
            </IconButton>
          )}
          <span className="font-medium text-sm">
            {view === "overview" && "Dive shared with"}
            {view === "add-person" && "Add person"}
            {view === "add-group" && "Add group"}
          </span>
        </div>

        {/* Body (scrollable) */}
        <div className="flex-1 overflow-y-auto px-4 py-2">
          {view === "overview" && (
            <Overview
              onAddPerson={() => setView("add-person")}
              onAddGroup={() => setView("add-group")}
              readers={readers}
              groupReaders={groupReaders}
              diveId={diveId}
              fetchAllReaders={fetchAllReaders}
            />
          )}

          {view === "add-person" && (
            <AddPerson diveId={diveId} fetchAllReaders={fetchAllReaders} />
          )}
          {view === "add-group" && (
            <AddGroup diveId={diveId} fetchAllReaders={fetchAllReaders} />
          )}
        </div>
      </div>
    </Popover>
  );
}

// ---- Overview ----
function Overview({
  onAddPerson,
  onAddGroup,
  diveId,
  readers,
  groupReaders,
  fetchAllReaders,
}: Readonly<{
  onAddPerson: () => void;
  onAddGroup: () => void;
  diveId: number | undefined;
  readers: User[];
  groupReaders: Group[];
  fetchAllReaders: () => void;
}>) {
  const { deleteWithToken } = useApi();

  async function deletePerson(id: number) {
    try {
      if (diveId == undefined) return;
      await deleteWithToken(`/v1/dives/${diveId}/readers`, [id], {});
      fetchAllReaders();
    } catch (err: unknown) {
      toast.error("failed to delete buddy");
      console.error(err);
      return false;
    }
  }
  async function deleteGroup(id: number | undefined) {
    try {
      if (diveId == undefined) return;
      await deleteWithToken(
        `/v1/dives/${diveId}/group-readers?groupId=${id}`,
        {},
        {}
      );
      fetchAllReaders();
    } catch (err: unknown) {
      toast.error("failed to delete group reader");
      console.error(err);
      return false;
    }
  }

  return (
    <div className="space-y-4">
      <section>
        <Header title="People" onAdd={onAddPerson} />
        <List dense>
          {readers.map((p) => (
            <ListItem key={p.id} disablePadding>
              <div className="flex justify-between w-full">
                <ListItemText primary={p.name} />
                <IconButton size="small" onClick={() => deletePerson(p.id)}>
                  <CrossIcon fontSize="small" />
                </IconButton>
              </div>
            </ListItem>
          ))}
        </List>
      </section>

      <section>
        <Header title="Groups" onAdd={onAddGroup} />
        <List dense>
          {groupReaders.map((g) => (
            <ListItem key={g.id} disablePadding>
              <div className="flex justify-between w-full">
                <ListItemText primary={g.name} />
                <IconButton size="small" onClick={() => deleteGroup(g.id)}>
                  <CrossIcon fontSize="small" />
                </IconButton>
              </div>
            </ListItem>
          ))}
        </List>
      </section>
    </div>
  );
}

function Header({
  title,
  onAdd,
}: Readonly<{ title: string; onAdd: () => void }>) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-xs font-semibold text-gray-600">{title}</span>
      <IconButton size="small" onClick={onAdd}>
        <AddIcon fontSize="medium" />
      </IconButton>
    </div>
  );
}

// ---- Add person view ----
function AddPerson({
  diveId,
  fetchAllReaders,
}: Readonly<{ diveId: number | undefined; fetchAllReaders: () => void }>) {
  const { postWithToken } = useApi();

  async function handleSubmitAddPerson(
    event: React.FormEvent<HTMLFormElement>
  ) {
    event.preventDefault();

    try {
      if (diveId == undefined) return;
      const formData = new FormData(event.currentTarget);
      const diveBuddies = formData.getAll("diveBuddy") as string[];
      await postWithToken(
        `/v1/dives/${diveId}/readers`,
        diveBuddies,
        {},
        "application/json"
      );
      toast.success("successfully added dive buddy!");
      fetchAllReaders();
    } catch (err: unknown) {
      toast.error("failed add dive buddy");
      console.error(err);
    }
  }
  return (
    <form className="flex flex-col gap-4" onSubmit={handleSubmitAddPerson}>
      <AutocompleteInput
        suburl="user"
        label="enter username"
        name="diveBuddy"
        multiple={true}
      />
      <input
        type="submit"
        value="Add buddy"
        className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg cursor-pointer transition-colors duration-200"
      />
    </form>
  );
}

// ---- Add group view  ----
function AddGroup({
  diveId,
  fetchAllReaders,
}: Readonly<{ diveId: number | undefined; fetchAllReaders: () => void }>) {
  const { postWithToken } = useApi();

  async function handleSubmitAddGroup(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (diveId == undefined) return;
    try {
      const formData = new FormData(event.currentTarget);
      const diveGroup = formData.get("groupName") as string;
      await postWithToken(
        `/v1/dives/${diveId}/group-readers`,
        diveGroup,
        {},
        "application/json"
      );
      toast.success("successfully added groups!");
      fetchAllReaders();
    } catch (err: unknown) {
      toast.error("failed add group");
      console.error(err);
    }
  }
  return (
    <form className="flex flex-col gap-4" onSubmit={handleSubmitAddGroup}>
      <AutocompleteInput
        suburl="group"
        label="enter group name"
        name="groupName"
        multiple={false}
      />
      <input
        type="submit"
        value="Add groups"
        className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg cursor-pointer transition-colors duration-200"
      />
    </form>
  );
}
